In [1]:
import pandas as pd
pd.__version__

'1.4.3'

In [2]:
import numpy as np

In [3]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [9]:
population_dict

{'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}

In [10]:
registration = [True,False,True,True]
registration = pd.Series(registration)
registration

0     True
1    False
2     True
3     True
dtype: bool

In [11]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [12]:
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [13]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [14]:
states.columns

Index(['population', 'area'], dtype='object')

In [15]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [16]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [17]:
pd.DataFrame(np.random.rand(3, 2),
columns=['foo', 'bar'],
index=['a', 'b', 'c'])

foo       bar
a  0.976810  0.688764
b  0.229816  0.224207
c  0.563571  0.270560

In [18]:
x = np.random.rand(3, 2)
x

array([[0.22263472, 0.28193623],
       [0.50993827, 0.03186064],
       [0.64793216, 0.94158664]])

In [19]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [20]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [21]:
x1 = pd.DataFrame(['a', 'b', 'c'], index=[1,3,5])
y1 = pd.DataFrame(['a1', 'b1', 'c1'], index=[2,3,8])
print(x1)
print(y1)

   0
1  a
3  b
5  c
    0
2  a1
3  b1
8  c1


In [22]:
#x1.index & y1.index
v = x1.index.intersection(y1.index)
print(v)

Int64Index([3], dtype='int64')


In [23]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [24]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [25]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [26]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [27]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [28]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [29]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [30]:
area = pd.Series({'California': 423967, 'Texas': 695662,
'New York': 141297, 'Florida': 170312,
'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127, 'Florida': 19552860,
'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [31]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [32]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [33]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [34]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [35]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [36]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [37]:
data.iloc[0,2]

90.41392608386974

In [38]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [39]:
data[1:3] # 以列來處理

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [40]:
data[data.density > 80] # 以列來處理

area       pop     density
California  423967  38332521   90.413926
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [41]:
import pandas as pd
import numpy as np

In [42]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [43]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [44]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [45]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [46]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [47]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [48]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [49]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [50]:
dd=pd.Series([5,1,9], index= [1,3,5])
dd

1    5
3    1
5    9
dtype: int64

In [51]:
dd.loc[1:3] # 參考到明確的索引

1    5
3    1
dtype: int64

In [52]:
dd.iloc[1:3] # 以隱含的python型態索引

3    1
5    9
dtype: int64

In [53]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [54]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [55]:
# Python資料科學學習手冊 p.121
rng = np.random.RandomState(42)
A = rng.randint(10, size=(3, 4))
A

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

In [56]:
# Row : Numpy used
# np.subtract(A, A[0]) ### Same as below
A - A[0]

array([[ 0,  0,  0,  0],
       [ 0,  6, -5,  2],
       [ 1,  1, -4,  3]])

In [57]:
# Column : Numpy used
B = A.T
C = B - B[1]
D = C.T
D

array([[ 3,  0,  4,  1],
       [-3,  0, -7, -3],
       [ 3,  0, -1,  3]])

In [58]:
df = pd.DataFrame(A, columns=list('QRST'))
# df - df.loc[0]   ### Same as below
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  0  6 -5  2
2  1  1 -4  3

In [59]:
# np.subtract(A.T, A.T[1]).T   ### Same as below
df.subtract(df['R'], axis=0)

Q  R  S  T
0  3  0  4  1
1 -3  0 -7 -3
2  3  0 -1  3

In [60]:
import numpy as np
import pandas as pd
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [62]:
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype = object
128 ms ± 1.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
3.78 ms ± 54.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [66]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [67]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [69]:
vals2.sum(), vals2.max(), vals2.min() 

(nan, nan, nan)

In [70]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [72]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [73]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [74]:
index = [('California', 2000), ('California', 2010),
('New York', 2000), ('New York', 2010),
('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
18976457, 19378102,
20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [76]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [77]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [78]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [82]:
a = np.array([[1,2,3,4],
           [2,3,5,8],
           [4,9,6,1]])
a

array([[1, 2, 3, 4],
       [2, 3, 5, 8],
       [4, 9, 6, 1]])

In [87]:
a[1:3,:]

array([[2, 3, 5, 8],
       [4, 9, 6, 1]])

In [89]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [90]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [91]:
pop_df = pd.DataFrame({'total': pop,
'under18': [9267089, 9284094,4687374, 4318033,5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [94]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [96]:
df = pd.DataFrame(np.random.rand(4, 2),
index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
columns=['data1', 'data2'])
df

data1     data2
a 1  0.990295  0.036894
  2  0.354667  0.992557
b 1  0.165125  0.528735
  2  0.535777  0.819605