In [1]:
import numpy
numpy.__version__

'1.23.0'

In [2]:
import numpy as np

In [3]:
np?

In [4]:
np.empty(3)

array([1.13199732e-311, 0.00000000e+000, 2.17519389e+243])

In [5]:
np.random.seed(0)
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))

In [6]:
print(x1)

[5 0 3 3 7 9]


In [7]:
x4 = np.random.randint(10, size = 6)

In [8]:
print(x4)

[4 3 4 4 8 4]


In [9]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [10]:
print("x3 ndi,: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndi,:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [11]:
print("x2 ndi,: ", x3.ndim)
print("x2 shape: ", x3.shape)
print("x2 size: ", x3.size)

x2 ndi,:  3
x2 shape:  (3, 4, 5)
x2 size:  60


In [12]:
print("x2 ndi,: ", x2.ndim)
print("x2 shape: ", x2.shape)
print("x2 size: ", x2.size)

x2 ndi,:  2
x2 shape:  (3, 4)
x2 size:  12


In [13]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [14]:
print(x4)
print(x1)

[4 3 4 4 8 4]
[5 0 3 3 7 9]


In [15]:
np.random.seed(0)
x5 = np.random.randint(10, size = 6)

In [16]:
print(x5)

[5 0 3 3 7 9]


In [17]:
print(x1)
print(x5)

[5 0 3 3 7 9]
[5 0 3 3 7 9]


In [18]:
x = np.arrange(10)
x

AttributeError: module 'numpy' has no attribute 'arrange'

In [19]:
x = np.arrange(10)
print(x)

AttributeError: module 'numpy' has no attribute 'arrange'

In [20]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[:5]

array([0, 1, 2, 3, 4])

In [22]:
x[4:7]

array([4, 5, 6])

In [23]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
x[3:5:-1]

array([], dtype=int32)

In [25]:
x[5:1:-1]

array([5, 4, 3, 2])

In [26]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [27]:
x.reshape((1,3))

array([[1, 2, 3]])

In [28]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [29]:
y = np.array([1,2,3])

In [30]:
y.reshape(1)

ValueError: cannot reshape array of size 3 into shape (1,)

In [31]:
y.reshape(1,)

ValueError: cannot reshape array of size 3 into shape (1,)

In [32]:
y.reshape(1,3)

array([[1, 2, 3]])

In [33]:
y = np.array([1,2,3])

In [34]:
y

array([1, 2, 3])

In [35]:
y.reshape(1,3)

array([[1, 2, 3]])

In [36]:
y = np.array([1,2,3])
y

array([1, 2, 3])

In [37]:
y.reshape((1,3))

array([[1, 2, 3]])

In [38]:
y = np.array([1,2,3])
y

array([1, 2, 3])

In [39]:
y.reshape(3,1)

array([[1],
       [2],
       [3]])

In [40]:
y = np.array([1,2,3])
y

array([1, 2, 3])

In [41]:
y[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [42]:
y = np.array([1,2,3])
y

array([1, 2, 3])

In [43]:
y[np.newaxis,:]

array([[1, 2, 3]])

In [44]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([99,99,99])
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6, 99, 99, 99])

In [45]:
x =[1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x, [3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [46]:
x1,x2,x3 = np.split(x, [4,5])
print(x1,x2,x3)

[ 1  2  3 99] [99] [3 2 1]


In [47]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
upper, lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [49]:
left, right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [50]:
import numpy as np
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [51]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.96 s ± 91.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [52]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [53]:
%timeit (1.0 / big_array)

3.27 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [56]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

ValueError: operands could not be broadcast together with shapes () (8,) (5,) 

In [57]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [58]:
y = np.zeros(10)
np.power(2, x, out=y[::2])

array([ 1.,  2.,  4.,  8., 16.])